name: Push new image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    environment:
      name: main

    runs-on: ubuntu-latest

    env:
      BRANCH: main

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}
        
    - name: Fetch latest changes
      run: git fetch origin main

    - name: Reset local branch to match remote
      run: git reset --hard origin/main
        
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.USER }}
        password: ${{ secrets.PASS }}

        
    - name: build and push image main
      run: |
        docker build -t gustavovl/notigest-back:$BRANCH .
        docker push gustavovl/notigest-back:$BRANCH